"""empty message

Revision ID: 2bc51bb8f774
Revises: 331302c3f310
Create Date: 2015-11-30 14:21:43.501300

"""

# revision identifiers, used by Alembic.
revision = '2bc51bb8f774'
down_revision = '331302c3f310'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    ### end Alembic commands ###
